version: '3.9'
services:
  db:
    image: postgres:16
    container_name: db_library
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_library
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports: ["3000:3000"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm ci && npm run start:dev"

volumes:
  pgdata:
